version: '3.8'

services:
  elesh-archivist:
    image: jmruland/elesh-archivist:latest
    container_name: elesh-archivist
    ports:
      - "5005:5005"
    volumes:
      - /mnt/infrastructure:/app # SINGLE volume mount!
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - MODEL_NAME=nomic-embed-text
      - LOG_LEVEL=INFO
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/infrastructure/.ollama:/root/.ollama
    restart: always
    networks:
      - backend

networks:
  backend:
