version: '3.8'

services:
  elesh-archivist:
    image: jmruland/elesh-archivist:latest
    container_name: elesh-archivist
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434
    volumes:
      - /mnt/infrastructure/elesh-archivist/lore:/app/lore
      - /mnt/infrastructure/elesh-archivist/prompts/system.txt:/app/system.txt
    ports:
      - "5005:5005"
