name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: yourdockerhubusername/elesh-archivist
  VERSION_FILE: VERSION

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Determine version
        id: versioning
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "Commit message: $COMMIT_MSG"

          if git diff HEAD~1 HEAD --name-only | grep -q "^$VERSION_FILE$"; then
            VERSION=$(cat $VERSION_FILE)
            echo "Using manually specified version: $VERSION"
          else
            VERSION=$(cat $VERSION_FILE)
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)

            if echo "$COMMIT_MSG" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'; then
              VERSION=$(echo "$COMMIT_MSG" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
              echo "Version from commit message: $VERSION"
            else
              PATCH=$((PATCH + 1))
              VERSION="$MAJOR.$MINOR.$PATCH"
              echo "$VERSION" > $VERSION_FILE
              git config user.name github-actions
              git config user.email github-actions@users.noreply.github.com
              git add $VERSION_FILE
              git commit -m "Auto-bump version to $VERSION"
              git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git
              git push origin HEAD:main
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.versioning.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest