name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: jmruland/elesh-archivist

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for version comparison

      - name: Set up Python for version bumping
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Extract version
        id: versioning
        run: |
          VERSION_FILE="VERSION"
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo "Commit message: $COMMIT_MSG"

          # Check if version was manually updated
          if git diff HEAD~1 HEAD --name-only | grep -q "^VERSION$"; then
            VERSION=$(cat $VERSION_FILE)
            echo "Using manually specified version: $VERSION"
          else
            VERSION=$(cat $VERSION_FILE)
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)

            if echo "$COMMIT_MSG" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'; then
              VERSION=$(echo "$COMMIT_MSG" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
              echo "Version from commit message: $VERSION"
            else
              PATCH=$((PATCH + 1))
              VERSION="$MAJOR.$MINOR.$PATCH"
              echo "$VERSION" > $VERSION_FILE
              git config user.name github-actions
              git config user.email github-actions@users.noreply.github.com
              git add $VERSION_FILE
              git commit -m "Auto-bump version to $VERSION"
              git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
            fi
          fi

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.versioning.outputs.VERSION }}